spring.application.name=tickets


# PostgreSQL DB connection
spring.datasource.url=jdbc:postgresql://localhost:5433/event_ticketing
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.hikari.connection-init-sql=SET TimeZone='Asia/Kolkata'
spring.datasource.hikari.data-source-properties.TimeZone=Asia/Kolkata
spring.datasource.hikari.data-source-properties.userTimezone=Asia/Kolkata


# JPA / Hibernate settings
spring.jpa.show-sql=true
    spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata



spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9090/realms/event-ticket-platform-realm
